#! /bin/sh

bspc config border_width        2
bspc config window_gap         33

bspc config split_ratio         0.43
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^4 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a file-roller floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a lxappearance floating=on center=true
bspc rule -a thunar floating=on center=true
bspc rule -a synaptic floating=on center=true

bspc config normal_border_color "#2d2d2d"
bspc config active_border_color "#ccff99"
bspc config focused_border_color "#ccff99"
#bspc config active_border_color "#FF6666"
#bspc config focused_border_color "#FF6666"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

## autostart the panel
#cd /home/robin/.bin/ && ./panel &
