#!/bin/sh

# Padding
bspc config top_padding $PANEL_HEIGHT

# Borders and gaps
bspc config border_width 10
bspc config window_gap 25
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc monitor -d one two three four five

# Border colors
bspc config normal_border_color "#000000"
#bspc config normal_private_border_color "#888888"
bspc config focused_border_color "#ffffff"
bspc config urgent_border_color "#b58900"
# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.5
bspc config focused_frame_opacity 0.5

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true

# Misc
bspc config split_ratio 0.43
# bspc config auto_alternate true
# bspc config auto_cancel true

# Set up displays
# bspc monitor --reset-desktops 1
# bspc monitor --add-desktops 2
# bspc monitor --remove-desktops 2


bspc rule -a tint2 floating=on manage=off
bspc rule -a Gimp desktop=^4 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a file-roller floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a lxappearance floating=on center=true
bspc rule -a thunar floating=on center=true
bspc rule -a synaptic floating=on center=true